### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zhyc9de** [nixxcode/pjsip-g729#1]
how to use the patch and is the patch match pjsip 2.6 ?

**Comment by shehrazjazib** [comment]
Are you successfully integrate G729 codec with your project? 
Kindly guide me, if you can. 
Thanks in advance

**Comment by zhyc9de** [comment]
u can easily use with this [project](https://github.com/VoiSmart/pjsip-android-builder)
edit `config.conf`, then build with `./configure CFLAGS=-fPIC --enable-g729-codec`

**Comment by shehrazjazib** [comment]
But as mentioned in given project, PJSIP 2.4.5 is very old version. i want to integrate G729 with PJSIP 2.7V.
 can i build PJSIP 2.7 with this [project](https://github.com/VoiSmart/pjsip-android-builder)
